In [1]:
import pandas as pd
import numpy as np
from datetime import datetime
dataframe=pd.read_csv("Automatic email content store.csv",delimiter="$")
dataframe.head() #topp 5 rows

       Date                              to                            raw
0  30/09/17       shubhi.prakash03@gmail.com  will be doing it by tomorrow
1  30/09/17  exampreparationonline@gmail.com  will be doing it by tomorrow
2  30/09/17  exampreparationonline@gmail.com  will be doing it by tomorrow
3  30/09/17       shubhi.prakash03@gmail.com  will be doing it by tomorrow
4  30/09/17       shubhi.prakash03@gmail.com  will be doing it by tomorrow

In [2]:
#function to find unique email address
def email_address_list(dataframe):
    email_dictionary={}
    for itr in range (0,len(dataframe)):
        if dataframe["to "][itr] in email_dictionary:
            email_dictionary[dataframe["to "][itr]]+=1
        else :
            email_dictionary[dataframe["to "][itr]]=1
    email_list=[]
    for key in email_dictionary.iterkeys():
        email_list.append(key)
    return email_list

print "Unique Email Address: \n", np.asarray(email_address_list(dataframe)).reshape(-1,1)

Unique Email Address:
[['ramthakkar07@gmail.com']
 ['limithakeerthi@gmail.com']
 ['nidhisaini05@gmail.com']
 ['sonuyannam@gmail.com']
 ['shubhi.prakash03@gmail.com']
 ['sachinsn231@gmail.com']
 ['abhishekguragol@gmail.com']
 ['chowdhuryshaif@rediffmail.com']
 ['exampreparationonline@gmail.com']
 ['pavithramurugan22@gmail.com']
 ['saha.swapankumar1@gmail.com']]

In [3]:
#function to find last date of conversation with that user
def last_date_of_conversation(dateframe):
    last_date={}
    for itr1 in range(0,len(dataframe)):
        if dataframe["to "][itr1] in last_date:
            last_date[dataframe["to "][itr1]]=dataframe["Date"][itr1]
        else:
            last_date[dataframe["to "][itr1]]=dataframe["Date"][itr1]
    dataframe["Last_date_of conversation"]=""
    
    for itr2 in range(0,len(dataframe)):
        dataframe["Last_date_of conversation"][itr2]=last_date[dataframe["to "][itr2]]
    
last_date_of_conversation(dataframe)
dataframe.head()

,Date,to,raw,Last_date_of conversation
0,30/09/17,shubhi.prakash03@gmail.com,will be doing it by tomorrow,30/09/17
1,30/09/17,exampreparationonline@gmail.com,will be doing it by tomorrow,03/10/17
2,30/09/17,exampreparationonline@gmail.com,will be doing it by tomorrow,03/10/17
3,30/09/17,shubhi.prakash03@gmail.com,will be doing it by tomorrow,30/09/17
4,30/09/17,shubhi.prakash03@gmail.com,will be doing it by tomorrow,30/09/17

In [4]:
#function to find the number of delays elapsed
def days_elapsed(dataframe):
    dataframe["days_elapsed"]=""
    for itr3 in range(0,len(dataframe)):    
        current_date=datetime(datetime.now().year,datetime.now().month,datetime.now().day)
        try:
            past_date=dataframe["Date"][itr3].split("/")
            past_date=datetime((2000+int(past_date[2])),int(past_date[1]),int(past_date[0]))
            dataframe["days_elapsed"][itr3]=(current_date-past_date).days
        except:
            pass
        
days_elapsed(dataframe)
dataframe.head()

,Date,to,raw,Last_date_of conversation,days_elapsed
0,30/09/17,shubhi.prakash03@gmail.com,will be doing it by tomorrow,30/09/17,252
1,30/09/17,exampreparationonline@gmail.com,will be doing it by tomorrow,03/10/17,252
2,30/09/17,exampreparationonline@gmail.com,will be doing it by tomorrow,03/10/17,252
3,30/09/17,shubhi.prakash03@gmail.com,will be doing it by tomorrow,30/09/17,252
4,30/09/17,shubhi.prakash03@gmail.com,will be doing it by tomorrow,30/09/17,252

In [5]:
#function to find word
def find_word_content(dataframe):
    for itr4 in range(0,len(dataframe)):
        content=str(dataframe["raw"][itr4]).split(" ")
        keyword_list=["Python","OpenCv","Machine Learning"]
        dataframe["Keyword_present"]=""
        for word in content:
            if word in keyword_list:
                dataframe["Keyword_present"][itr4]= dataframe["Keyword_present"][itr4] + " " + word

find_word_content(dataframe)
dataframe.head()

,Date,to,raw,Last_date_of conversation,days_elapsed,Keyword_present
0,30/09/17,shubhi.prakash03@gmail.com,will be doing it by tomorrow,30/09/17,252,
1,30/09/17,exampreparationonline@gmail.com,will be doing it by tomorrow,03/10/17,252,
2,30/09/17,exampreparationonline@gmail.com,will be doing it by tomorrow,03/10/17,252,
3,30/09/17,shubhi.prakash03@gmail.com,will be doing it by tomorrow,30/09/17,252,
4,30/09/17,shubhi.prakash03@gmail.com,will be doing it by tomorrow,30/09/17,252,